spring:
  kafka:
    bootstrap-servers: 192.168.0.112:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        request.timeout.ms: 60000
        delivery.timeout.ms: 120000
        connections.max.idle.ms: 300000

    consumer:
      group-id: demo-group-remote
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.example.kafkademo.model.Message
        session.timeout.ms: 60000
        heartbeat.interval.ms: 20000
        request.timeout.ms: 60000

    client-id: kafka-demo-client
    properties:
      request.timeout.ms: 60000
      connections.max.idle.ms: 300000
      reconnect.backoff.ms: 1000
      retry.backoff.ms: 1000

logging:
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka: DEBUG
    org.apache.kafka.clients.NetworkClient: TRACE